/*
	File: fn_initClientFunct.sqf
	Author: Casperento
*/
if !(isNil "allClientFunct") exitWith {allClientFunct=[];};
cxp_clientFunctReady = false;

//Funcao basica para iniciar todas as do cliente
CXPSV_fnc_receiveClientFunct = compileFinal "
	missionNamespace setVariable [""cxp_cashMaoo"",""bafTuirY_ncioe9f""];
	missionNamespace setVariable [""cxp_cashBancoo"",""kniroNEKI0_yu""];
	{
		_name = _x select 0;
		_code = _x select 1;
		_compile = formatText[""%1 = %2;"",_name,_code];
		if (isServer) then {
			call compile str(_compile);
		} else {
			call compileFinal str(_compile);
		};
		publicVariable _name;
	} forEach allClientFunct;
	cxp_clientFunctReady = true;
";
publicVariable "CXPSV_fnc_receiveClientFunct";

fnc_functName = {
	params [["_str","",[""]],["_prefixo","",[""]]];
	private _strF = _str splitString "\._";
	_strF deleteAt (count _strF-1);
	_strF = _strF select (count _strF-1);
	private _sLimpa = format["%1_fnc_%2",_prefixo,_strF];
	_sLimpa
};

allClientFunct = [];
{
	_arq = (_x select 0);
	_preF = (_x select 1);
	_fName = [_arq,_preF] call fnc_functName;
	_codigo = compileFinal preprocessFileLineNumbers _arq;
	allClientFunct pushBack [_fName,_codigo];
} forEach [
	/* [diretorio,prefixo] */
	// clientFunctions
	["\life_server\clientFunctions\fn_initAddActions.sqf","cxp"],
	["\life_server\clientFunctions\fn_initCiv.sqf","cxp"],
	["\life_server\clientFunctions\fn_initCop.sqf","cxp"],
	["\life_server\clientFunctions\fn_initGbSysDonClient.sqf","cxp"],
	["\life_server\clientFunctions\fn_initMedic.sqf","cxp"],
	["\life_server\clientFunctions\fn_setupActions.sqf","cxp"],
	["\life_server\clientFunctions\fn_setupEVH.sqf","cxp"],
	["\life_server\clientFunctions\fn_survival.sqf","cxp"],
	// actions
	["\life_server\clientFunctions\actions\fn_apreenderItens.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_arrestAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_baternaporta.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_catchFish.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_cook.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_copCrush.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_craftAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_desmontarBarraca.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_dropFishingNet.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_escortAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_estuprar.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_gather.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_gatherObject.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_gutAnimal.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_healHospital.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_impoundAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_mine.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_montarBarraca.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_packupSpikes.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_parachuteEspecial.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_pickupAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_pickupItem.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_pickupMoney.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_pickupSomeItem.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_pulloutAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_putInCar.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_removeContainer.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_repairTruck.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_restrainAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_robAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_searchAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_searchVehAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_seizePlayerAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_sitdown.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_stopEscorting.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_suicideBomb.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_surrender.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_ticketAction.sqf","cxp"],
	["\life_server\clientFunctions\actions\fn_unrestrain.sqf","cxp"],
	// addActions
	["\life_server\clientFunctions\addActions\fn_atmMenu.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_buyLicense.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_captureHideout.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_chopShopMenu.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_clothingMenu.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_dpFinish.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_fedCamDisplay.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_getDPMission.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_menuPrefeituraOPEN.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_newsBroadcast.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_numberText.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_postBail.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_processAction.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_questionDealer.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_roubarConv.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_safeFix.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_safeOpen.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_serviceChopper.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_storeVehicle.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_vAHload.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_vehicleShopMenu.sqf","cxp"],
	["\life_server\clientFunctions\addActions\fn_virtMenu.sqf","cxp"],
    ["\life_server\clientFunctions\items\fn_flashbang.sqf","cxp"],
	// bounty
	["\life_server\clientFunctions\bounty\fn_alvoKilled.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_getBounty.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_handleDowned.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_initBounty.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_removeLocalBounty.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_removerBountyLic.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_removerBountyLicAct.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_setBounty.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_setGroupTrackMarker.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_trackBounty.sqf","cxp"],
	["\life_server\clientFunctions\bounty\fn_updateBountyListLocal.sqf","cxp"],
	// cellphone
	["\life_server\clientFunctions\cellphone\fn_cellPhoneCheck.sqf","cxp"],
	["\life_server\clientFunctions\cellphone\fn_deleteMessage.sqf","cxp"],
	["\life_server\clientFunctions\cellphone\fn_lbChanged.sqf","cxp"],
	["\life_server\clientFunctions\cellphone\fn_messagesMenu.sqf","cxp"],
	["\life_server\clientFunctions\cellphone\fn_replyMessage.sqf","cxp"],
	["\life_server\clientFunctions\cellphone\fn_setupCellPhone.sqf","cxp"],
	// cfgBasic
	["\life_server\clientFunctions\cfgBasic\fn_craftCfg.sqf","cxp"],
	["\life_server\clientFunctions\cfgBasic\fn_houseConfig.sqf","cxp"],
	["\life_server\clientFunctions\cfgBasic\fn_itemWeight.sqf","cxp"],
	["\life_server\clientFunctions\cfgBasic\fn_vehicleAnimate.sqf","cxp"],
	["\life_server\clientFunctions\cfgBasic\fn_vehicleWeightCfg.sqf","cxp"],
	// civilian
	["\life_server\clientFunctions\civilian\fn_civMarkers.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_demoChargeTimer.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_gagAction.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_gagged.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_jail.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_jailMe.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_knockedOut.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_knockoutAction.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_perdeuRabo.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_removeGagAction.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_removeLicenses.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_robPerson.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_robReceive.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_tazed.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_tieing.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_tieingAction.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_tieingActionb.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_tieingb.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_untie.sqf","cxp"],
	["\life_server\clientFunctions\civilian\fn_untieb.sqf","cxp"],
	// cop
	["\life_server\clientFunctions\cop\fn_arrestDialogArrest.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_bountyReceive.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_breathalyzer.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_containerInvSearch.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_copLights.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_copMarkers.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_copSearch.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_copSiren.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_copSiren2.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_doorAnimate.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_licenseCheck.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_licensesRead.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_placeableCancel.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_placeablePlace.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_placeablesInit.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_placeablesMenu.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_placeablesPlaceComplete.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_placeablesRemoveAll.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_radar.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_repairDoor.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_restrain.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_searchClient.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_seizeClient.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_sirenLights.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_speedCamera.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_spikeStripEffect.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_ticketGive.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_ticketPaid.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_ticketPay.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_ticketPrompt.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_vehInvSearch.sqf","cxp"],
	["\life_server\clientFunctions\cop\fn_wantedGrab.sqf","cxp"],
	// economy
	["\life_server\clientFunctions\economy\fn_marketGrab.sqf","cxp"],
	["\life_server\clientFunctions\economy\fn_openEconomy.sqf","cxp"],
	["\life_server\clientFunctions\economy\fn_retrievePrices.sqf","cxp"],
	["\life_server\clientFunctions\economy\fn_updateEconomy.sqf","cxp"],
	["\life_server\clientFunctions\economy\fn_updatePrice.sqf","cxp"],
	// functions
	["\life_server\clientFunctions\functions\fn_AAN.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_abrirMenTerm.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_accType.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_actionKeyHandler.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_animDynSync.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_animSync.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_antiSellBug.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_autoMessages.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_autoSave.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_broadcast.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_buyWithGang.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_calcMoneyRemote.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_calWeightDiff.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_checkMap.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_clearVehicleAmmo.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_concordTerm.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_convertStrToArr.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_corpse.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_custPlaySound.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_discordTerm.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_dropItems.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_escInterupt.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_fetchCfgDetails.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_fetchDeadGear.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_fetchVehInfo.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_forceEnter.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_gateOpener.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_geradordeefeitos.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_giveDiff.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_handleDamage.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_handleInv.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_handleItem.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_hintDinamico.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_hintTggGZ.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_initGangZoneModule.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_initVirtualExtraInv.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_inString.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_inventoryClosed.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_inventoryOpened.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_isDamaged.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_isUIDActive.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_jumpFnc.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_keyHandler.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_limparInvPlayer.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_loadDeadGear.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_loadGear.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_logeOut.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_menuPrefeituraUPDATE.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_nearATM.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_nearestDoor.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_nearUnits.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_onFired.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_onGetOutMan.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_onPlayerKilled.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_onPlayerRespawn.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_onPutItem.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_onTakeItem.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_pAssalto.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_plaquinhasInitList.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_playerInteractionMenu.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_playerSkins.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_playerTags.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_plVehInitList.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_postNewsBroadcast.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_procInitList.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_pullOutVeh.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_pushObject.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_receiveItem.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_revealObjects.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_saveGear.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_say3D.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_setFuel.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_simDisable.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_soundDevice.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_stripDownPlayer.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_updateBaseLic.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_validarBase.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_vrtExtInvDROP.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_vrtExtInvOPEN.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_vrtExtInvUPDATE.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_whereAmI.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_wpShopDesconto.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_welcomeCredits.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_changeCbList.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_resetarCbList.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_localizarMarcador.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_avisarPvpEntorno.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_completeBugTracking.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_showRRMessage.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_openBarracaInv.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_novoDonator.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_receiveMoney.sqf","cxp"],
	["\life_server\clientFunctions\functions\fn_msgSafezone.sqf","cxp"],
	// gangs
	["\life_server\clientFunctions\gangs\fn_areaCapture.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_createGang.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangCreated.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangDisband.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangDisbanded.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangInvite.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangInvitePlayer.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangKick.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangLeave.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangMenu.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangNewLeader.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangSetBase.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangSetBaseMenu.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_gangUpgrade.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_getNamesExUID.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_initGang.sqf","cxp"],
	["\life_server\clientFunctions\gangs\fn_getOffmem.sqf","cxp"],
	// guiFunct
	["\life_server\clientFunctions\guiFunct\fn_bankDepositAll.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_bankDeposit.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_bankTransfer.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_bankWithdrawAll.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_bankWithdraw.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_craft.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_craftUpdate.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_craftUpdateFilter.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_displayHandler.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_garageLBChange.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_giveItem.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_hudSetup.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_hudUpdate.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_hudUpdateInfo.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_impoundMenu.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_initMapFilter.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_insureCar.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_movesMenu.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_notify.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_pardon.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_pickupItems.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_progressBar.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_safeInventory.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_safeStore.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_safeTake.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_sAssaltoMSG.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_sellGarage.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_setMapPosition.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_spawnConfirm.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_spawnMenu.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_spawnPointCfg.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_spawnPointSelected.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_unimpound.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_useItem.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_vehicleGarage.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_wantedAddP.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_wantedInfo.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_wantedList.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_wantedMenu.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_wireTransfer.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_reportarBug.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_cellphone.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_giveMoney.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_keyDrop.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_keyGive.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_keyMenu.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_pOpenMenu.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_pUpdateMenu.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_removeItem.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_sOnChar.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_sOnSliderChange.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_settingsMenu.sqf","cxp"],
	["\life_server\clientFunctions\guiFunct\fn_updateViewDistance.sqf","cxp"],
	// housing
	["\life_server\clientFunctions\housing\fn_buyHouse.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_buyHouseGarage.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_containerMenu.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_copBreakDoor.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_copHouseOwner.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_garageRefund.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_getBuildingPositions.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_houseMenu.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_initHouses.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_lightHouse.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_lightHouseAction.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_lockHouse.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_lockupHouse.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_placeContainer.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_playerInBuilding.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_raidHouse.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_sellHouse.sqf","cxp"],
	["\life_server\clientFunctions\housing\fn_sellHouseGarage.sqf","cxp"],
	// items
	["\life_server\clientFunctions\items\fn_blastingCharge.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_boltcutter.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_defuseKit.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_jerryCanRefuel.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_jerryRefuel.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_lockpick.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_placestorage.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_spikeStrip.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_storageBox.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_adrenalineShot.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_campFire.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_cocainaE.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_drinkbeer.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_drinkwhiskey.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_heroinaE.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_meth.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_useCigarette.sqf","cxp"],
	["\life_server\clientFunctions\items\fn_weed.sqf","cxp"],
	// medical
	["\life_server\clientFunctions\medical\fn_apagarItemLista.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_cancelarChamado.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_curarRabo.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_deleteClienteProx.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_initDeadListClient.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_initSamuExtraFunc.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_lancarBoteSalvaVidas.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_loadDeadList.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_localizarDefunto.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_macaScript.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_medicLights.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_medicMarkers.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_medicSiren.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_medicSiren2.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_medicSirenLights.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_medInteractionMenu.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_multaAutomatica.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_pacienteAceito.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_recebListClient.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_respawned.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_revived.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_reviveInst.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_revivePlayer.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_rmCorpseArr.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_seizeClientMed.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_telaDeMorte.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_terminarCurarAnal.sqf","cxp"],
	["\life_server\clientFunctions\medical\fn_onLbChangeDeadList.sqf","cxp"],
	// session
	["\life_server\clientFunctions\session\fn_dataQuery.sqf","CXPSKT"],
	["\life_server\clientFunctions\session\fn_insertPlayerInfo.sqf","CXPSKT"],
	["\life_server\clientFunctions\session\fn_requestReceived.sqf","CXPSKT"],
	["\life_server\clientFunctions\session\fn_syncData.sqf","CXPSKT"],
	["\life_server\clientFunctions\session\fn_tazeRagdoll.sqf","CXPSKT"],
	["\life_server\clientFunctions\session\fn_updatePartial.sqf","CXPSKT"],
	["\life_server\clientFunctions\session\fn_updateRequest.sqf","CXPSKT"],
	// shops
	["\life_server\clientFunctions\shops\fn_3dPreviewDisplay.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_3dPreviewExit.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_3dPreviewInit.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_buyClothes.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_changeClothes.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_chopShopSelection.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_chopShopSell.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_clothingFilter.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_fuelLBChange.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_fuelStatOpen.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_levelCheck.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_vehicleShopBuy.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_vehicleShopLBChange.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_virtBuy.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_virtSell.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_virtUpdate.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_weaponShopAccs.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_weaponShopBuySell.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_weaponShopFilter.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_weaponShopMags.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_weaponShopMenu.sqf","cxp"],
	["\life_server\clientFunctions\shops\fn_weaponShopSelection.sqf","cxp"],
	// vAH
	["\life_server\clientFunctions\vAH\fn_vAHBuy.sqf","cxp"],
	["\life_server\clientFunctions\vAH\fn_vAHCheckItem.sqf","cxp"],
	["\life_server\clientFunctions\vAH\fn_vAHLoadInventory.sqf","cxp"],
	["\life_server\clientFunctions\vAH\fn_vAHReciever.sqf","cxp"],
	["\life_server\clientFunctions\vAH\fn_vAHSelect.sqf","cxp"],
	["\life_server\clientFunctions\vAH\fn_vAHSell.sqf","cxp"],
	["\life_server\clientFunctions\vAH\fn_vAHTakeBack.sqf","cxp"],
	// vehicle
	["\life_server\clientFunctions\vehicle\fn_addVehicle2Chain.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_colorVehicle.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_deviceMine.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_fuelRefuelCar.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_fuelStore.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_fuelSupply.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_lockVehicle.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_openInventory.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_vehicleColor3DRefresh.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_vehicleOwners.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_vehicleWeight.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_vehInventory.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_vehStoreAllItem.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_vehStoreItem.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_vehTakeItem.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_vehTakeAllItem.sqf","cxp"],
	["\life_server\clientFunctions\vehicle\fn_vInteractionMenu.sqf","cxp"]
];
if (count allClientFunct > 0) then {publicVariable "allClientFunct";[] call CXPSV_fnc_receiveClientFunct;}else{diag_log "allClientFunct vazio no initClientFunct";};